title: [Python DawTools]
description: [PySide/PyQt widgets for daw projects]
remote_theme: pmarsceill/just-the-docs
color_scheme: "mpi"

# Aux links for the upper right navigation
aux_links:
  "DawTools on GitHub":
    - "//github.com/MadPonyInteractive/daw-tools"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
